name: Python Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' # Assuming Python 3.13 based on pyproject.toml
    - name: Install uv
      run: pip install uv
    - name: Create virtual environment and install dependencies
      run: |
        uv venv # Create a virtual environment
        uv pip install -e .[test] # Install project in editable mode with test extras
    - name: Run tests
      env:
        PYTHONPATH: .
      run: pytest 